routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPanier.yml"
    prefix:   /panier
    
routingProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix:   /
    
routingCommandes:
    resource: "@EcommerceBundle/Resources/config/routing/routingCommandes.yml"
    prefix:   /
    
ecommerce_adminProduits:
    resource: "@EcommerceBundle/Resources/config/routing/produits.yml"
    prefix:   /admin/produits
    
ecommerce_adminCategories:
    resource: "@EcommerceBundle/Resources/config/routing/categories.yml"
    prefix:   /admin/categories
    
ecommerce_adminCommandes:
    resource: "@EcommerceBundle/Resources/config/routing/commandes.yml"
    prefix:   /admin/commandes