adminPages_index:
    path:     /
    defaults: { _controller: "PagesBundle:Pages:index" }
    methods:  GET

adminPages_show:
    path:     /{id}/show
    defaults: { _controller: "PagesBundle:Pages:show" }
    methods:  GET

adminPages_new:
    path:     /new
    defaults: { _controller: "PagesBundle:Pages:new" }
    methods:  [GET, POST]

adminPages_edit:
    path:     /{id}/edit
    defaults: { _controller: "PagesBundle:Pages:edit" }
    methods:  [GET, POST]

adminPages_delete:
    path:     /{id}/delete
    defaults: { _controller: "PagesBundle:Pages:delete" }
    methods:  DELETE
