<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    public function  byFacture($user){
        $qb=$this->createQueryBuilder('f')
                ->select('f')
                ->where('f.utilisateur = :utilisateur')
                ->andWhere('f.reference !=0')
                ->orderBy('f.id')
        ->setParameter('utilisateur', $user);
       return $qb->getQuery()->getResult();
    }
}
