<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategorie($categorie)
    {
        $qb=$this->createQueryBuilder('u')
                ->select('u')
                ->where('u.categorie = :categorie')
                ->andWhere('u.disponible = 1')
                ->orderBy('u.id')
                ->setParameter(':categorie', $categorie);
        
        return $qb->getQuery()->getResult();
    }
    
    public function recherche($chaine){
        $qb=$this->createQueryBuilder('p')
                ->select('p')               
                ->where('p.nom = :nom')
                ->andWhere('p.disponible = 1')
                ->orderBy('p.id')
                ->setParameter(':nom', $chaine);
        
        return $qb->getQuery()->getResult();
    }
    
    public function findArray(array $array){
        $qb=$this->createQueryBuilder('p')
                ->select('p')
                ->where('p.id IN (:array)')
                ->setParameter('array', $array);
        
        return $qb->getQuery()->getResult();
    }
}
