<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateursAdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateursAdressesRepository extends EntityRepository
{
    public function byAdresse($user){
        $qb= $this->createQueryBuilder('a')
                ->select('a')
                ->where('a.utilisateur = :utilisateur')
                ->orderBy('a.id')
                ->setParameter('utilisateur',$user);
        
      return  $qb->getQuery()->getResult();
    }
}
